# Generated by Django 2.2.7 on 2019-12-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20191206_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='shift',
            field=models.CharField(blank=True, choices=[('PM', 'PM'), ('AM', 'AM')], help_text='Shift', max_length=10),
        ),
    ]
